version: '2'

services:
  app:
    image: 'bachelorprojekt:latest'
    build:
      context: .
    container_name: 'api'
    depends_on:
      - db
    ports:
      - '8080:8080'
  db:
    image: 'postgres:13.1-alpine'
    container_name: 'db'
    environment:
      - POSTGRES_USER=admin@admin.de
      - POSTGRES_PASSWORD=admin
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
